import { useState } from 'react';
import { genreColors } from '../game/catalog';
import { inspectCustomer, makeInitialState, moveBook, nextDay, openShop, searchStep } from '../game/simulation';
import type { Book, GameState } from '../game/types';

export default function App(){
 const [game,setGame]=useState<GameState>(makeInitialState()); const [activeCustomer,setActiveCustomer]=useState<string|null>(null); const [dragged,setDragged]=useState<string|null>(null);
 const book=(id:string|null)=>game.books.find(b=>b.id===id);
 const onDrop=(slot:number|null)=>{if(dragged){setGame(g=>moveBook(g,dragged,slot));setDragged(null);return;} if(activeCustomer&&slot!==null)setGame(g=>searchStep(g,activeCustomer,slot));};
 const selectBook=(item:Book)=>{if(game.isOpen&&activeCustomer){setGame(g=>searchStep(g,activeCustomer,item.slot??-1));return;} setGame(g=>({...g,selectedBookId:item.id,inspectedBookId:null,message:`${item.title} · ${item.author}`}));};
 const inspected=book(game.inspectedBookId);
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">✳</span><span>paperbacks</span></div><div className="day-label">Day {game.day}<span className="open-dot" data-open={game.isOpen}/>{game.isOpen?'Open':'Before opening'}</div><div className="wallet"><span>Today’s till</span><strong>${game.money}</strong></div></header>
  <section className="stage-wrap"><div className="scene-heading"><div><p className="eyebrow">A little shop on Alder Street</p><h1>Make room for a good read.</h1></div><button className="shop-button" onClick={()=>setGame(g=>openShop(g))}>{game.isOpen?'Close for today':'Open the shop'}</button></div>
   <div className="store-scene" onDragOver={e=>e.preventDefault()}>
    <div className="window"><div className="window-light"/><span>OPEN</span><div className="window-sill"/></div><div className="wall-note">SECOND-HAND BOOKS<br/><small>come in, take your time</small></div>
    <div className="shelf-unit"><div className="shelf-top"/><div className="book-row">{Array.from({length:game.capacity},(_,slot)=>{const item=game.books.find(b=>b.slot===slot); return <div className="slot" key={slot} onDragOver={e=>e.preventDefault()} onDrop={()=>onDrop(slot)} onClick={()=>activeCustomer&&!item?setGame(g=>({...g,message:'They glance at the empty space.'})):undefined}>{item&&<button className={`book ${game.selectedBookId===item.id?'selected':''} ${activeCustomer?'search-target':''}`} style={{'--cover':item.cover} as React.CSSProperties} draggable onDragStart={()=>setDragged(item.id)} onDragEnd={()=>setDragged(null)} onClick={e=>{e.stopPropagation();selectBook(item)}} onDoubleClick={e=>{e.stopPropagation();setGame(g=>({...g,inspectedBookId:item.id,selectedBookId:null}))}} aria-label={`${item.title} by ${item.author}`}><span className="spine-title">{item.title}</span><span className="spine-mark">✳</span></button>}</div>})}</div><div className="shelf-board"/><div className="shelf-legs"/></div>
    <div className="counter"><div className="register"><span/><i/></div><div className="counter-top"/><div className="counter-front"/></div>
    {game.customers.map((customer,index)=><button key={customer.id} className={`customer customer-${index} ${activeCustomer===customer.id?'customer-active':''}`} style={{left:`${Math.min(75,customer.x)}%`,'--person':customer.color} as React.CSSProperties} onClick={()=>{setActiveCustomer(activeCustomer===customer.id?null:customer.id);setGame(g=>({...g,message:inspectCustomer(customer)}))}}><span className="thought">{customer.state==='found'?'♡':customer.thought}</span><span className="head"/><span className="body"/><span className="legs"/></button>)}
    <div className="floor-line"/><div className="floorboards"/>
   </div>
   <div className="scene-status"><span className="status-mark">✳</span>{game.message}<span className="scene-hint">{game.isOpen?'Click a reader, then a book to help them browse.':'Drag books onto the shelf. Double-click to read a cover.'}</span></div>
  </section>
  <section className="lower-panel"><div className="pile-panel"><div className="panel-title"><div><p className="eyebrow">Waiting to be shelved</p><h2>Floor pile <span>{game.books.filter(b=>b.slot===null).length}</span></h2></div><span className="drag-note">drag a book to place it</span></div><div className="pile" onDragOver={e=>e.preventDefault()} onDrop={()=>onDrop(null)}>{game.books.filter(b=>b.slot===null).length===0?<p className="empty-pile">The floor is clear. Lovely.</p>:game.books.filter(b=>b.slot===null).map(item=><button key={item.id} className="pile-book" style={{'--cover':item.cover} as React.CSSProperties} draggable onDragStart={()=>setDragged(item.id)} onDragEnd={()=>setDragged(null)} onClick={()=>selectBook(item)} onDoubleClick={()=>setGame(g=>({...g,inspectedBookId:item.id}))}><span>{item.title}</span></button>)}</div></div>
   <aside className="upgrade-panel"><div className="panel-title"><div><p className="eyebrow">A good day’s work</p><h2>Tomorrow, maybe…</h2></div><span className="coins">${game.money}</span></div><div className="upgrade-row"><span className="upgrade-icon">＋</span><div><strong>Another shelf</strong><small>Add room for more stories</small></div><button disabled={game.money<30||game.capacity>=16} onClick={()=>setGame(g=>({...g,money:g.money-30,capacity:g.capacity+2,message:'A new shelf arrives overnight.'}))}>$30</button></div><button className="next-day" onClick={()=>setGame(g=>nextDay(g))}>End the day <span>↗</span></button></aside>
  </section>
  {inspected&&<div className="inspect-backdrop" onClick={()=>setGame(g=>({...g,inspectedBookId:null}))}><article className="book-card" onClick={e=>e.stopPropagation()}><button className="close-card" onClick={()=>setGame(g=>({...g,inspectedBookId:null}))}>×</button><div className="cover-art" style={{'--cover':inspected.cover} as React.CSSProperties}><span>✳</span><strong>{inspected.title}</strong><small>{inspected.author}</small></div><p className="eyebrow">A second-hand find</p><h2>{inspected.title}</h2><p className="byline">by {inspected.author}</p><p className="genre"><i style={{background:genreColors[inspected.genre]}}/>{inspected.genre}</p><button className="shop-button" onClick={()=>setGame(g=>({...g,inspectedBookId:null}))}>Back to the shelves</button></article></div>}
  <footer><span>Take your time. The books aren’t going anywhere.</span><span>Every book finds a reader.</span></footer>
 </main>
}
